services:
  scraper:
    build: .
    volumes:
      - ./data/db:/app/data/db
      - ./data/logs:/app/data/logs
    command: python src/main_scripts/run_scraper_schedule.py
    working_dir: /app
    environment:
      - RUN_MODE=scheduled      # Scheduling mode
      - LOG_LEVEL=INFO          # how much info to log
      - standard_minute_interval=30
      - fast_minute_interval=15
      - rapid_minute_interval=8
      - location_days_interval=7
    restart: unless-stopped
