services:
  rapid:
    build: .
    volumes:
      - ./data/db:/app/data/db
      - ./data/logs:/app/data/logs
    command: python src/main_scripts/run_scraper_schedule.py
    working_dir: /app
    environment:
      - RUN_MODE=scheduled      # Scheduling mode
      - LOG_LEVEL=INFO          # how much info to log
      - SCRAPER_TYPE=rapid
      - MINUTE_INTERVAL=5
      - MAX_WORKERS=1
      - SLEEP_IN_SECONDS=0.1
    restart: unless-stopped
  fast:
    build: .
    volumes:
      - ./data/db:/app/data/db
      - ./data/logs:/app/data/logs
    command: python src/main_scripts/run_scraper_schedule.py
    working_dir: /app
    environment:
      - RUN_MODE=scheduled      # Scheduling mode
      - LOG_LEVEL=INFO          # how much info to log
      - SCRAPER_TYPE=fast
      - MINUTE_INTERVAL=15
      - MAX_WORKERS=1
      - SLEEP_IN_SECONDS=0.1
    restart: unless-stopped

  standard:
    build: .
    volumes:
      - ./data/db:/app/data/db
      - ./data/logs:/app/data/logs
    command: python src/main_scripts/run_scraper_schedule.py
    working_dir: /app
    environment:
      - RUN_MODE=scheduled      # Scheduling mode
      - LOG_LEVEL=INFO          # how much info to log
      - SCRAPER_TYPE=standard
      - MINUTE_INTERVAL=60
      - MAX_WORKERS=1
      - SLEEP_IN_SECONDS=0.1
    restart: unless-stopped

  locations:
    build: .
    volumes:
      - ./data/db:/app/data/db
      - ./data/logs:/app/data/logs
    command: python src/main_scripts/run_scraper_schedule.py
    working_dir: /app
    environment:
      - RUN_MODE=scheduled      # Scheduling mode
      - LOG_LEVEL=INFO          # how much info to log
      - SCRAPER_TYPE=locations
      - LOCATION_DAY_INTERVAL=7

    restart: unless-stopped
