name: deployable_scraper
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - sqlite
  - pytest
  - pip:
      - git+https://github.com/Mo1l/scraping_charger_data.git
      - -e .
  